version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3011:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5011/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5011:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pcots
      - JWT_SECRET=your_jwt_secret_key_here
      - PORT=5000

  postgres:
    image: postgres:14
    ports:
      - "5443:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pcots

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1036:1025" # SMTP server
      - "8036:8025" # Web UI

volumes:
  postgres_data: